/**
 * Multiple-choice question builder for textbook vocabulary.
 *
 * Three question shapes, mixed inside one session:
 *   ja2meaning — see the Japanese word, pick the meaning
 *   meaning2ja — see the meaning, pick the Japanese word
 *   reading    — see a kanji word, pick its reading
 *
 * Distractors matter more than the stems: meanings and words are drawn from
 * the same book (same part of speech when possible) so the wrong options are
 * genuinely confusable, and wrong *readings* are generated by mutating the
 * right one the way learners actually mishear it — voicing, long vowels and
 * small つ — instead of pairing it with an unrelated word's reading.
 */
import type { TextbookWord } from '../types'

export type ChoiceKind = 'ja2meaning' | 'meaning2ja' | 'reading'

export interface ChoiceQuestion {
  word: TextbookWord
  kind: ChoiceKind
  /** what the learner sees */
  prompt: string
  options: string[]
  answer: number
}

const HAS_KANJI = /[㐀-鿿]/

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

// --- plausible misreadings --------------------------------------------------

const VOICED: Record<string, string> = {
  か: 'が', き: 'ぎ', く: 'ぐ', け: 'げ', こ: 'ご',
  さ: 'ざ', し: 'じ', す: 'ず', せ: 'ぜ', そ: 'ぞ',
  た: 'だ', ち: 'ぢ', つ: 'づ', て: 'で', と: 'ど',
  は: 'ば', ひ: 'び', ふ: 'ぶ', へ: 'べ', ほ: 'ぼ',
}
const UNVOICED: Record<string, string> = Object.fromEntries(
  Object.entries(VOICED).map(([k, v]) => [v, k]),
)
/** kana whose long vowel is spelled with a trailing う */
const U_LONG = 'おこそとのほもよろごぞどぼぽょしゅちゅ'
/** kana whose long vowel is spelled with a trailing い */
const I_LONG = 'えけせてねへめれげぜでべぺ'
/** a small つ can only appear before these */
const SOKUON_NEXT = 'かきくけこさしすせそたちつてとぱぴぷぺぽ'

/** One round of single-edit mutations of `reading`. */
function mutateOnce(reading: string): string[] {
  const out = new Set<string>()
  const chars = Array.from(reading)

  const swap = (i: number, to: string) => {
    const copy = [...chars]
    copy[i] = to
    out.add(copy.join(''))
  }

  chars.forEach((c, i) => {
    if (VOICED[c]) swap(i, VOICED[c])
    if (UNVOICED[c]) swap(i, UNVOICED[c])
    // long vowel dropped or added
    if (c === 'う' && i > 0 && U_LONG.includes(chars[i - 1])) {
      out.add(chars.filter((_, j) => j !== i).join(''))
    }
    if (c === 'い' && i > 0 && I_LONG.includes(chars[i - 1])) {
      out.add(chars.filter((_, j) => j !== i).join(''))
    }
    if (U_LONG.includes(c) && chars[i + 1] !== 'う') {
      out.add([...chars.slice(0, i + 1), 'う', ...chars.slice(i + 1)].join(''))
    }
    if (I_LONG.includes(c) && chars[i + 1] !== 'い') {
      out.add([...chars.slice(0, i + 1), 'い', ...chars.slice(i + 1)].join(''))
    }
    // small つ dropped or added
    if (c === 'っ') out.add(chars.filter((_, j) => j !== i).join(''))
    else if (i > 0 && chars[i - 1] !== 'っ' && SOKUON_NEXT.includes(c)) {
      out.add([...chars.slice(0, i), 'っ', ...chars.slice(i)].join(''))
    }
  })

  out.delete(reading)
  return [...out]
}

/**
 * Wrong readings a learner might plausibly write. Single edits first; if the
 * word is short enough that those run out (てんいん yields only two), edits of
 * those edits fill the gap — still recognisably the same word, still wrong.
 */
function misreadings(reading: string, want: number): string[] {
  const first = mutateOnce(reading)
  if (first.length >= want) return first
  const out = new Set(first)
  for (const variant of first) {
    for (const second of mutateOnce(variant)) {
      if (second !== reading) out.add(second)
      if (out.size >= want) break
    }
    if (out.size >= want) break
  }
  return [...out]
}

// --- question building ------------------------------------------------------

/** Draw `n` distinct values, preferring words that share `word`'s part of speech. */
function distractors(
  word: TextbookWord,
  pool: TextbookWord[],
  valueOf: (w: TextbookWord) => string,
  n: number,
): string[] {
  const taken = new Set([valueOf(word)])
  const picked: string[] = []
  const samePos = pool.filter((w) => w.p === word.p && w.id !== word.id)
  const rest = pool.filter((w) => w.p !== word.p && w.id !== word.id)

  for (const group of [shuffle(samePos), shuffle(rest)]) {
    for (const w of group) {
      if (picked.length >= n) break
      const v = valueOf(w)
      if (!v || taken.has(v)) continue
      taken.add(v)
      picked.push(v)
    }
  }
  return picked
}

function meaningOf(zhFirst: boolean) {
  return (w: TextbookWord) => (zhFirst ? w.zh : w.en)
}

function build(
  word: TextbookWord,
  kind: ChoiceKind,
  pool: TextbookWord[],
  zhFirst: boolean,
  optionCount: number,
): ChoiceQuestion | null {
  const meaning = meaningOf(zhFirst)
  let prompt: string
  let correct: string
  let wrong: string[]

  if (kind === 'reading') {
    if (!HAS_KANJI.test(word.w) || word.r === word.w) return null
    prompt = word.w
    correct = word.r
    const want = optionCount - 1
    const mis = shuffle(misreadings(word.r, want)).slice(0, want)
    // Last resort: other words' readings, but only ones of comparable length —
    // a one-mora option next to a four-mora answer gives the game away.
    if (mis.length < want) {
      const near = shuffle(
        pool.filter((w) => w.r !== word.r && Math.abs(w.r.length - word.r.length) <= 1),
      )
      for (const w of near) {
        if (mis.length >= want) break
        if (!mis.includes(w.r)) mis.push(w.r)
      }
    }
    wrong = mis
  } else if (kind === 'meaning2ja') {
    prompt = meaning(word)
    correct = word.w
    wrong = distractors(word, pool, (w) => w.w, optionCount - 1)
  } else {
    prompt = word.w
    correct = meaning(word)
    wrong = distractors(word, pool, meaning, optionCount - 1)
  }

  if (wrong.length < optionCount - 1) return null
  const options = shuffle([correct, ...wrong])
  return { word, kind, prompt, options, answer: options.indexOf(correct) }
}

export interface BuildOptions {
  /** which question shapes to mix in; defaults to all three */
  kinds?: ChoiceKind[]
  zhFirst: boolean
  optionCount?: number
}

/**
 * One question per word, in a random order. A word whose requested shape
 * cannot be built (a kana-only word asked for its reading, say) falls back to
 * another shape rather than being dropped.
 */
export function buildChoiceQuestions(
  words: TextbookWord[],
  pool: TextbookWord[],
  { kinds = ['ja2meaning', 'meaning2ja', 'reading'], zhFirst, optionCount = 4 }: BuildOptions,
): ChoiceQuestion[] {
  const questions: ChoiceQuestion[] = []
  words.forEach((word, i) => {
    const order = [kinds[i % kinds.length], ...kinds]
    for (const kind of order) {
      const q = build(word, kind, pool, zhFirst, optionCount)
      if (q) {
        questions.push(q)
        return
      }
    }
  })
  return shuffle(questions)
}
